---

- ansible.builtin.include_tasks: "install.yml"
- ansible.builtin.include_tasks: "modules.yml"
- ansible.builtin.include_tasks: "config.yml"

- name: "{{ beat_name }} | finish: Start beat"
  become: true
  ansible.builtin.service:
    name: "{{ beat_name }}"
    state: restarted
